version: '3.8'

services:
  web:
    build: .
    container_name: aiohttp_prisma_p3_server
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/my_db?schema=public
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    command: python aiohttp_prisma_server.py

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

